title: Daniel Hayward's Blog
description: Essays and fiction from Daniel Hayward
author: Daniel Hayward
baseurl: ""
url: "https://danielphayward.com"

# Pandoc settings
markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'

# Collections
collections:
  posts:
    output: true
    permalink: /:slug/