title: Daniel Hayward's Blog
description: Essays and fiction from Daniel Hayward
author: Daniel Hayward
baseurl: ""
plugins: ["jekyll-feed"]
url: "https://danielphayward.com"
markdown: kramdown
kramdown:
  input: GFM
collections:
  posts:
    output: true
    permalink: /:slug/