title: Daniel Hayward's Blog
description: Essays and fiction from Daniel Hayward
author: Daniel Hayward
baseurl: ""
url: "https://danielphayward.com"

plugins: 
  - jekyll-feed
  
# Back to kramdown
markdown: kramdown

# Collections
collections:
  posts:
    output: true
    permalink: /:slug/