title: Daniel Hayward's Blog
description: Essays and fiction from Daniel Hayward
author: Daniel Hayward
baseurl: ""
url: "https://danielphayward.com"

plugins: 
  - jekyll-feed
  - jekyll-pandoc

# Pandoc settings
markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - lua-filter: 'pandoc-sidenote.lua' 

# Collections
collections:
  posts:
    output: true
    permalink: /:slug/